title: "Aaron Rennick Portfolio"
description: "Game Design • 2D/3D Art • Technical Art"
baseurl: "/portfolio-page"
url: "https://darkaaron999.github.io"

# Disable Cayman theme
theme: null

plugins: []

header_pages:
  - index.html
  - about.html
  - contact.html

include:
  - assets

markdown: kramdown
kramdown:
  input: GFM
